### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by aqrit** [mklarqvist/positional-popcount#25]
I'm thinking about doing a rewrite, here are some random thoughts:

1. `pospopcnt_csa_sse()` implies two unnecessary temp variables. It could be [rewritten](http://haroldbot.nl/index.html?q=%28%28a+%26+b%29+%7C+%28%28a+%5E+b%29+%26+c%29%29+%3D%3D+%28%28%28a+%5E+b%29+%7C+%28a+%5E+c%29%29+%5E+%28%28a+%5E+b%29+%5E+c%29%29) as:
b ^= a;
a ^= c;
c ^= b; // xor sum
b |= a;
b ^= c; // carry

2. The throughput of a CSA  is better than its latency. So it is probably best to keep two independent CSAs executing in parallel. Specifically, passing `v1` as a [in/out] parameter
to **every** bottom tier CSA may create a serial dependency. 

3. At least two passes through the CSA Unit are required for the CSA Unit to pay for itself.
So we may be able to better space loads inside the loop body...
If we process half a loop, before before initially dropping into the loop body, then we can spend the back half of the loop pre-loading for the next pass.

4. Assuming two loads per cycle on AVX2 machines… It may be better to trade out instructions for more i/o?  Maybe spill the output of the CSA Unit into a buffer,  then we could go back and do another --or several more-- passes of 16:1 reductions before accumulating.

**Comment by lemire** [comment]
@aqrit : I have AVX-512 hardware... if you are interested in having access to it (ssh/linux), let me know.

> So it is probably best to keep two independent CSAs executing in parallel.

It would be fun to find out whether this improves the throughput.

> Maybe spill the output of the CSA Unit into a buffer, then we could go back and do another --or several more-- passes of 16:1 reductions before accumulating.

That sounds intriguing.

**Comment by mklarqvist** [comment]
Any progress on this @aqrit ? I've been toying with your points 2) and 4) without much success.

**Comment by aqrit** [comment]
I got bogged down writing asm style code for number (2)... (trying to setup groups of 1 load + 4 independent logic ops) I don't have anything working yet.

Plus I might be totally wrong :-)

**Comment by aqrit** [comment]
(2) probably doesn't do anything for us. 

The last 3 CSA ops are serial and have a lot of empty slots.
The first 3 CSA ops will be serial only when using all `v1`s.
So OoOE probably overlaps the top & bottom of the loop.

All other instances/uses of `v1` can be hidden by non-`v1` CSA ops.

**Comment by mklarqvist** [comment]
Thanks for the update @aqrit . I also did not manage to get any improvement from (1), (2) and (4).

**Comment by aqrit** [comment]
(1) saves 2 registers for avx. Those registers may be useful, if one is doing something fancy like counting only the position of the highest set bit in each integer. For say a Nehalem CPU, I'd expect (1) to remove ~32 instructions (4 cache lines), 10 cycles from each loop iteration.  A Haswell+ cpus running SSE code have "move elimination", so it will still save bytes but probably not cycles.

(4) I hope this will save something. Lets say we have 64KiB of data, we could trade 128 "acculumates" for 128 CSAs...?
This would seem to be the same trade we're making by doing by doing the intial CSAs.

**Comment by aqrit** [comment]
Food for thought:

The Carry-Save-Unit could use half-adders to go deeper.

Currently the CSU uses only full-adders and goes 5 lines deep.
It processes 16 lines of input before accumulating.

If 4 half-adders were appended to the CSU to take it to a depth of 9 lines...
It could process 256 lines of input before accumulating.

Half-adders are much less efficient... but they should still be cheaper than the accumulate operation.

Whether it is worth trading out a couple of the full-adders to add even more half-adders is unknown.
Also we’ve only got so many registers, etc.
Lets say the accumulate step cost 16 ops and a half-adder cost 2 ops... we definitively wouldn’t want 8 half-adders.

**Comment by mklarqvist** [comment]
Thanks @aqrit . Any updates? We're back to hacking away at this.

**Comment by aqrit** [comment]
No progress or updates.

Stray thought:
If 16-bit 1-hots are fed into the Carry-Save-Unit then its output should average 1 set bit every 16-bits. For SSE2, [really fast bitset decoding for average densities](https://lemire.me/blog/2019/05/03/really-fast-bitset-decoding-for-average-densities/) could be used to find & count the set positions in the output.

**Comment by mklarqvist** [comment]
Thanks. I'll close this for now.
